const cities = [
  { ddd: 11, state: "SP", name: "EMBU" },
  { ddd: 11, state: "SP", name: "VÁRZEA PAULISTA" },
  { ddd: 11, state: "SP", name: "VARGEM GRANDE PAULISTA" },
  { ddd: 11, state: "SP", name: "VARGEM" },
  { ddd: 11, state: "SP", name: "TUIUTI" },
  { ddd: 11, state: "SP", name: "TABOÃO DA SERRA" },
  { ddd: 11, state: "SP", name: "SUZANO" },
  { ddd: 11, state: "SP", name: "SÃO ROQUE" },
  { ddd: 11, state: "SP", name: "SÃO PAULO" },
  { ddd: 11, state: "SP", name: "SÃO LOURENÇO DA SERRA" },
  { ddd: 11, state: "SP", name: "SÃO CAETANO DO SUL" },
  { ddd: 11, state: "SP", name: "SÃO BERNARDO DO CAMPO" },
  { ddd: 11, state: "SP", name: "SANTO ANDRÉ" },
  { ddd: 11, state: "SP", name: "SANTANA DE PARNAÍBA" },
  { ddd: 11, state: "SP", name: "SANTA ISABEL" },
  { ddd: 11, state: "SP", name: "SALTO" },
  { ddd: 11, state: "SP", name: "SALESÓPOLIS" },
  { ddd: 11, state: "SP", name: "RIO GRANDE DA SERRA" },
  { ddd: 11, state: "SP", name: "RIBEIRÃO PIRES" },
  { ddd: 11, state: "SP", name: "POÁ" },
  { ddd: 11, state: "SP", name: "PIRAPORA DO BOM JESUS" },
  { ddd: 11, state: "SP", name: "PIRACAIA" },
  { ddd: 11, state: "SP", name: "PINHALZINHO" },
  { ddd: 11, state: "SP", name: "PEDRA BELA" },
  { ddd: 11, state: "SP", name: "OSASCO" },
  { ddd: 11, state: "SP", name: "NAZARÉ PAULISTA" },
  { ddd: 11, state: "SP", name: "MORUNGABA" },
  { ddd: 11, state: "SP", name: "MOGI DAS CRUZES" },
  { ddd: 11, state: "SP", name: "MAUÁ" },
  { ddd: 11, state: "SP", name: "MAIRIPORÃ" },
  { ddd: 11, state: "SP", name: "MAIRINQUE" },
  { ddd: 11, state: "SP", name: "JUQUITIBA" },
  { ddd: 11, state: "SP", name: "JUNDIAÍ" },
  { ddd: 11, state: "SP", name: "JOANÓPOLIS" },
  { ddd: 11, state: "SP", name: "JARINU" },
  { ddd: 11, state: "SP", name: "JANDIRA" },
  { ddd: 11, state: "SP", name: "ITUPEVA" },
  { ddd: 11, state: "SP", name: "ITU" },
  { ddd: 11, state: "SP", name: "ITATIBA" },
  { ddd: 11, state: "SP", name: "ITAQUAQUECETUBA" },
  { ddd: 11, state: "SP", name: "ITAPEVI" },
  { ddd: 11, state: "SP", name: "ITAPECERICA DA SERRA" },
  { ddd: 11, state: "SP", name: "IGARATÁ" },
  { ddd: 11, state: "SP", name: "GUARULHOS" },
  { ddd: 11, state: "SP", name: "GUARAREMA" },
  { ddd: 11, state: "SP", name: "FRANCO DA ROCHA" },
  { ddd: 11, state: "SP", name: "FRANCISCO MORATO" },
  { ddd: 11, state: "SP", name: "FERRAZ DE VASCONCELOS" },
  { ddd: 11, state: "SP", name: "EMBU-GUAÇU" },
  { ddd: 11, state: "SP", name: "DIADEMA" },
  { ddd: 11, state: "SP", name: "COTIA" },
  { ddd: 11, state: "SP", name: "CARAPICUÍBA" },
  { ddd: 11, state: "SP", name: "CAMPO LIMPO PAULISTA" },
  { ddd: 11, state: "SP", name: "CAJAMAR" },
  { ddd: 11, state: "SP", name: "CAIEIRAS" },
  { ddd: 11, state: "SP", name: "CABREÚVA" },
  { ddd: 11, state: "SP", name: "BRAGANÇA PAULISTA" },
  { ddd: 11, state: "SP", name: "BOM JESUS DOS PERDÕES" },
  { ddd: 11, state: "SP", name: "BIRITIBA-MIRIM" },
  { ddd: 11, state: "SP", name: "BARUERI" },
  { ddd: 11, state: "SP", name: "ATIBAIA" },
  { ddd: 11, state: "SP", name: "ARUJÁ" },
  { ddd: 11, state: "SP", name: "ARAÇARIGUAMA" },
  { ddd: 11, state: "SP", name: "ALUMÍNIO" },
  { ddd: 16, state: "SP", name: "BRODÓSQUI" },
  { ddd: 16, state: "SP", name: "VISTA ALEGRE DO ALTO" },
  { ddd: 16, state: "SP", name: "TRABIJU" },
  { ddd: 16, state: "SP", name: "TAQUARITINGA" },
  { ddd: 16, state: "SP", name: "TAQUARAL" },
  { ddd: 16, state: "SP", name: "TAIÚVA" },
  { ddd: 16, state: "SP", name: "TAIAÇU" },
  { ddd: 16, state: "SP", name: "TABATINGA" },
  { ddd: 16, state: "SP", name: "SERTÃOZINHO" },
  { ddd: 16, state: "SP", name: "SERRANA" },
  { ddd: 16, state: "SP", name: "SERRA AZUL" },
  { ddd: 16, state: "SP", name: "SÃO SIMÃO" },
  { ddd: 16, state: "SP", name: "SÃO JOSÉ DA BELA VISTA" },
  { ddd: 16, state: "SP", name: "SÃO JOAQUIM DA BARRA" },
  { ddd: 16, state: "SP", name: "SÃO CARLOS" },
  { ddd: 16, state: "SP", name: "SANTO ANTÔNIO DA ALEGRIA" },
  { ddd: 16, state: "SP", name: "SANTA ROSA DE VITERBO" },
  { ddd: 16, state: "SP", name: "SANTA LÚCIA" },
  { ddd: 16, state: "SP", name: "SANTA ERNESTINA" },
  { ddd: 16, state: "SP", name: "SANTA CRUZ DA ESPERANÇA" },
  { ddd: 16, state: "SP", name: "SALES OLIVEIRA" },
  { ddd: 16, state: "SP", name: "RINCÃO" },
  { ddd: 16, state: "SP", name: "RIFAINA" },
  { ddd: 16, state: "SP", name: "RIBEIRÃO PRETO" },
  { ddd: 16, state: "SP", name: "RIBEIRÃO CORRENTE" },
  { ddd: 16, state: "SP", name: "RIBEIRÃO BONITO" },
  { ddd: 16, state: "SP", name: "RESTINGA" },
  { ddd: 16, state: "SP", name: "PRADÓPOLIS" },
  { ddd: 16, state: "SP", name: "PONTAL" },
  { ddd: 16, state: "SP", name: "PITANGUEIRAS" },
  { ddd: 16, state: "SP", name: "PEDREGULHO" },
  { ddd: 16, state: "SP", name: "PATROCÍNIO PAULISTA" },
  { ddd: 16, state: "SP", name: "ORLÂNDIA" },
  { ddd: 16, state: "SP", name: "NUPORANGA" },
  { ddd: 16, state: "SP", name: "NOVA EUROPA" },
  { ddd: 16, state: "SP", name: "MOTUCA" },
  { ddd: 16, state: "SP", name: "MORRO AGUDO" },
  { ddd: 16, state: "SP", name: "MONTE ALTO" },
  { ddd: 16, state: "SP", name: "MIGUELÓPOLIS" },
  { ddd: 16, state: "SP", name: "MATÃO" },
  { ddd: 16, state: "SP", name: "LUÍS ANTÔNIO" },
  { ddd: 16, state: "SP", name: "JERIQUARA" },
  { ddd: 16, state: "SP", name: "JARDINÓPOLIS" },
  { ddd: 16, state: "SP", name: "JABOTICABAL" },
  { ddd: 16, state: "SP", name: "ITUVERAVA" },
  { ddd: 16, state: "SP", name: "ITIRAPUÃ" },
  { ddd: 16, state: "SP", name: "ITÁPOLIS" },
  { ddd: 16, state: "SP", name: "IPUÃ" },
  { ddd: 16, state: "SP", name: "IGARAPAVA" },
  { ddd: 16, state: "SP", name: "IBITINGA" },
  { ddd: 16, state: "SP", name: "IBATÉ" },
  { ddd: 16, state: "SP", name: "GUATAPARÁ" },
  { ddd: 16, state: "SP", name: "GUARIBA" },
  { ddd: 16, state: "SP", name: "GUARÁ" },
  { ddd: 16, state: "SP", name: "GAVIÃO PEIXOTO" },
  { ddd: 16, state: "SP", name: "FRANCA" },
  { ddd: 16, state: "SP", name: "FERNANDO PRESTES" },
  { ddd: 16, state: "SP", name: "DUMONT" },
  { ddd: 16, state: "SP", name: "DOURADO" },
  { ddd: 16, state: "SP", name: "DOBRADA" },
  { ddd: 16, state: "SP", name: "CRISTAIS PAULISTA" },
  { ddd: 16, state: "SP", name: "CRAVINHOS" },
  { ddd: 16, state: "SP", name: "CÁSSIA DOS COQUEIROS" },
  { ddd: 16, state: "SP", name: "CÂNDIDO RODRIGUES" },
  { ddd: 16, state: "SP", name: "CAJURU" },
  { ddd: 16, state: "SP", name: "BURITIZAL" },
  { ddd: 16, state: "SP", name: "BORBOREMA" },
  { ddd: 16, state: "SP", name: "BOA ESPERANÇA DO SUL" },
  { ddd: 16, state: "SP", name: "BATATAIS" },
  { ddd: 16, state: "SP", name: "BARRINHA" },
  { ddd: 16, state: "SP", name: "ARARAQUARA" },
  { ddd: 16, state: "SP", name: "ARAMINA" },
  { ddd: 16, state: "SP", name: "AMÉRICO BRASILIENSE" },
  { ddd: 16, state: "SP", name: "ALTINÓPOLIS" },
  { ddd: 17, state: "SP", name: "VOTUPORANGA" },
  { ddd: 17, state: "SP", name: "VITÓRIA BRASIL" },
  { ddd: 17, state: "SP", name: "VIRADOURO" },
  { ddd: 17, state: "SP", name: "VALENTIM GENTIL" },
  { ddd: 17, state: "SP", name: "URUPÊS" },
  { ddd: 17, state: "SP", name: "URÂNIA" },
  { ddd: 17, state: "SP", name: "UNIÃO PAULISTA" },
  { ddd: 17, state: "SP", name: "UCHOA" },
  { ddd: 17, state: "SP", name: "UBARANA" },
  { ddd: 17, state: "SP", name: "TURMALINA" },
  { ddd: 17, state: "SP", name: "TRÊS FRONTEIRAS" },
  { ddd: 17, state: "SP", name: "TERRA ROXA" },
  { ddd: 17, state: "SP", name: "TANABI" },
  { ddd: 17, state: "SP", name: "TABAPUÃ" },
  { ddd: 17, state: "SP", name: "SEVERÍNIA" },
  { ddd: 17, state: "SP", name: "SEBASTIANÓPOLIS DO SUL" },
  { ddd: 17, state: "SP", name: "SÃO JOSÉ DO RIO PRETO" },
  { ddd: 17, state: "SP", name: "SÃO JOÃO DE IRACEMA" },
  { ddd: 17, state: "SP", name: "SÃO JOÃO DAS DUAS PONTES" },
  { ddd: 17, state: "SP", name: "SÃO FRANCISCO" },
  { ddd: 17, state: "SP", name: "SANTA SALETE" },
  { ddd: 17, state: "SP", name: "SANTA RITA D'OESTE" },
  { ddd: 17, state: "SP", name: "SANTANA DA PONTE PENSA" },
  { ddd: 17, state: "SP", name: "SANTA FÉ DO SUL" },
  { ddd: 17, state: "SP", name: "SANTA CLARA D'OESTE" },
  { ddd: 17, state: "SP", name: "SANTA ALBERTINA" },
  { ddd: 17, state: "SP", name: "SANTA ADÉLIA" },
  { ddd: 17, state: "SP", name: "SALES" },
  { ddd: 17, state: "SP", name: "RUBINÉIA" },
  { ddd: 17, state: "SP", name: "RIOLÂNDIA" },
  { ddd: 17, state: "SP", name: "POTIRENDABA" },
  { ddd: 17, state: "SP", name: "POPULINA" },
  { ddd: 17, state: "SP", name: "PONTES GESTAL" },
  { ddd: 17, state: "SP", name: "PONTALINDA" },
  { ddd: 17, state: "SP", name: "POLONI" },
  { ddd: 17, state: "SP", name: "PIRANGI" },
  { ddd: 17, state: "SP", name: "PINDORAMA" },
  { ddd: 17, state: "SP", name: "PEDRANÓPOLIS" },
  { ddd: 17, state: "SP", name: "PAULO DE FARIA" },
  { ddd: 17, state: "SP", name: "PARISI" },
  { ddd: 17, state: "SP", name: "PARANAPUÃ" },
  { ddd: 17, state: "SP", name: "PARAÍSO" },
  { ddd: 17, state: "SP", name: "PALMEIRA D'OESTE" },
  { ddd: 17, state: "SP", name: "PALMARES PAULISTA" },
  { ddd: 17, state: "SP", name: "PALESTINA" },
  { ddd: 17, state: "SP", name: "OUROESTE" },
  { ddd: 17, state: "SP", name: "ORINDIÚVA" },
  { ddd: 17, state: "SP", name: "ONDA VERDE" },
  { ddd: 17, state: "SP", name: "OLÍMPIA" },
  { ddd: 17, state: "SP", name: "NOVO HORIZONTE" },
  { ddd: 17, state: "SP", name: "NOVA LUZITÂNIA" },
  { ddd: 17, state: "SP", name: "NOVAIS" },
  { ddd: 17, state: "SP", name: "NOVA GRANADA" },
  { ddd: 17, state: "SP", name: "NOVA CASTILHO" },
  { ddd: 17, state: "SP", name: "NOVA CANAÃ PAULISTA" },
  { ddd: 17, state: "SP", name: "NOVA ALIANÇA" },
  { ddd: 17, state: "SP", name: "NIPOÃ" },
  { ddd: 17, state: "SP", name: "NHANDEARA" },
  { ddd: 17, state: "SP", name: "NEVES PAULISTA" },
  { ddd: 17, state: "SP", name: "MONTE AZUL PAULISTA" },
  { ddd: 17, state: "SP", name: "MONTE APRAZÍVEL" },
  { ddd: 17, state: "SP", name: "MONÇÕES" },
  { ddd: 17, state: "SP", name: "MIRASSOLÂNDIA" },
  { ddd: 17, state: "SP", name: "MIRASSOL" },
  { ddd: 17, state: "SP", name: "MIRA ESTRELA" },
  { ddd: 17, state: "SP", name: "MESÓPOLIS" },
  { ddd: 17, state: "SP", name: "MERIDIANO" },
  { ddd: 17, state: "SP", name: "MENDONÇA" },
  { ddd: 17, state: "SP", name: "MARINÓPOLIS" },
  { ddd: 17, state: "SP", name: "MARAPOAMA" },
  { ddd: 17, state: "SP", name: "MAGDA" },
  { ddd: 17, state: "SP", name: "MACEDÔNIA" },
  { ddd: 17, state: "SP", name: "MACAUBAL" },
  { ddd: 17, state: "SP", name: "JOSÉ BONIFÁCIO" },
  { ddd: 17, state: "SP", name: "JALES" },
  { ddd: 17, state: "SP", name: "JACI" },
  { ddd: 17, state: "SP", name: "JABORANDI" },
  { ddd: 17, state: "SP", name: "ITAJOBI" },
  { ddd: 17, state: "SP", name: "IRAPUÃ" },
  { ddd: 17, state: "SP", name: "IPIGUÁ" },
  { ddd: 17, state: "SP", name: "INDIAPORÃ" },
  { ddd: 17, state: "SP", name: "ICÉM" },
  { ddd: 17, state: "SP", name: "IBIRÁ" },
  { ddd: 17, state: "SP", name: "GUZOLÂNDIA" },
  { ddd: 17, state: "SP", name: "GUARANI D'OESTE" },
  { ddd: 17, state: "SP", name: "GUARACI" },
  { ddd: 17, state: "SP", name: "GUAPIAÇU" },
  { ddd: 17, state: "SP", name: "GUAÍRA" },
  { ddd: 17, state: "SP", name: "GENERAL SALGADO" },
  { ddd: 17, state: "SP", name: "GASTÃO VIDIGAL" },
  { ddd: 17, state: "SP", name: "FLOREAL" },
  { ddd: 17, state: "SP", name: "FERNANDÓPOLIS" },
  { ddd: 17, state: "SP", name: "ESTRELA D'OESTE" },
  { ddd: 17, state: "SP", name: "EMBAÚBA" },
  { ddd: 17, state: "SP", name: "ELISIÁRIO" },
  { ddd: 17, state: "SP", name: "DOLCINÓPOLIS" },
  { ddd: 17, state: "SP", name: "DIRCE REIS" },
  { ddd: 17, state: "SP", name: "COSMORAMA" },
  { ddd: 17, state: "SP", name: "COLÔMBIA" },
  { ddd: 17, state: "SP", name: "COLINA" },
  { ddd: 17, state: "SP", name: "CEDRAL" },
  { ddd: 17, state: "SP", name: "CATIGUÁ" },
  { ddd: 17, state: "SP", name: "CATANDUVA" },
  { ddd: 17, state: "SP", name: "CARDOSO" },
  { ddd: 17, state: "SP", name: "CAJOBI" },
  { ddd: 17, state: "SP", name: "BEBEDOURO" },
  { ddd: 17, state: "SP", name: "BARRETOS" },
  { ddd: 17, state: "SP", name: "BÁLSAMO" },
  { ddd: 17, state: "SP", name: "BADY BASSITT" },
  { ddd: 17, state: "SP", name: "AURIFLAMA" },
  { ddd: 17, state: "SP", name: "ASPÁSIA" },
  { ddd: 17, state: "SP", name: "ARIRANHA" },
  { ddd: 17, state: "SP", name: "APARECIDA D'OESTE" },
  { ddd: 17, state: "SP", name: "AMÉRICO DE CAMPOS" },
  { ddd: 17, state: "SP", name: "ÁLVARES FLORENCE" },
  { ddd: 17, state: "SP", name: "ALTAIR" },
  { ddd: 17, state: "SP", name: "ADOLFO" },
  { ddd: 18, state: "SP", name: "SANTO ANTÔNIO DO ARACANGUA" },
  { ddd: 18, state: "SP", name: "ZACARIAS" },
  { ddd: 18, state: "SP", name: "VALPARAÍSO" },
  { ddd: 18, state: "SP", name: "TURIÚBA" },
  { ddd: 18, state: "SP", name: "TUPI PAULISTA" },
  { ddd: 18, state: "SP", name: "TEODORO SAMPAIO" },
  { ddd: 18, state: "SP", name: "TARUMÃ" },
  { ddd: 18, state: "SP", name: "TARABAI" },
  { ddd: 18, state: "SP", name: "TACIBA" },
  { ddd: 18, state: "SP", name: "SUZANÁPOLIS" },
  { ddd: 18, state: "SP", name: "SUD MENNUCCI" },
  { ddd: 18, state: "SP", name: "SÃO JOÃO DO PAU D'ALHO" },
  { ddd: 18, state: "SP", name: "SANTÓPOLIS DO AGUAPEÍ" },
  { ddd: 18, state: "SP", name: "SANTO EXPEDITO" },
  { ddd: 18, state: "SP", name: "SANTO ANASTÁCIO" },
  { ddd: 18, state: "SP", name: "SANTA MERCEDES" },
  { ddd: 18, state: "SP", name: "SANDOVALINA" },
  { ddd: 18, state: "SP", name: "SALMOURÃO" },
  { ddd: 18, state: "SP", name: "SAGRES" },
  { ddd: 18, state: "SP", name: "RUBIÁCEA" },
  { ddd: 18, state: "SP", name: "ROSANA" },
  { ddd: 18, state: "SP", name: "RINÓPOLIS" },
  { ddd: 18, state: "SP", name: "RIBEIRÃO DOS ÍNDIOS" },
  { ddd: 18, state: "SP", name: "REGENTE FEIJÓ" },
  { ddd: 18, state: "SP", name: "RANCHARIA" },
  { ddd: 18, state: "SP", name: "QUATÁ" },
  { ddd: 18, state: "SP", name: "PRESIDENTE VENCESLAU" },
  { ddd: 18, state: "SP", name: "PRESIDENTE PRUDENTE" },
  { ddd: 18, state: "SP", name: "PRESIDENTE EPITÁCIO" },
  { ddd: 18, state: "SP", name: "PRESIDENTE BERNARDES" },
  { ddd: 18, state: "SP", name: "PRACINHA" },
  { ddd: 18, state: "SP", name: "PLATINA" },
  { ddd: 18, state: "SP", name: "PLANALTO" },
  { ddd: 18, state: "SP", name: "PIRAPOZINHO" },
  { ddd: 18, state: "SP", name: "PIQUEROBI" },
  { ddd: 18, state: "SP", name: "PIACATU" },
  { ddd: 18, state: "SP", name: "PEREIRA BARRETO" },
  { ddd: 18, state: "SP", name: "PENÁPOLIS" },
  { ddd: 18, state: "SP", name: "PEDRINHAS PAULISTA" },
  { ddd: 18, state: "SP", name: "PAULICÉIA" },
  { ddd: 18, state: "SP", name: "PARAPUÃ" },
  { ddd: 18, state: "SP", name: "PARAGUAÇU PAULISTA" },
  { ddd: 18, state: "SP", name: "PANORAMA" },
  { ddd: 18, state: "SP", name: "PALMITAL" },
  { ddd: 18, state: "SP", name: "PACAEMBU" },
  { ddd: 18, state: "SP", name: "OURO VERDE" },
  { ddd: 18, state: "SP", name: "OSVALDO CRUZ" },
  { ddd: 18, state: "SP", name: "NOVA INDEPENDÊNCIA" },
  { ddd: 18, state: "SP", name: "NOVA GUATAPORANGA" },
  { ddd: 18, state: "SP", name: "NARANDIBA" },
  { ddd: 18, state: "SP", name: "NANTES" },
  { ddd: 18, state: "SP", name: "MURUTINGA DO SUL" },
  { ddd: 18, state: "SP", name: "MONTE CASTELO" },
  { ddd: 18, state: "SP", name: "MIRANTE DO PARANAPANEMA" },
  { ddd: 18, state: "SP", name: "MIRANDÓPOLIS" },
  { ddd: 18, state: "SP", name: "MARTINÓPOLIS" },
  { ddd: 18, state: "SP", name: "MARIÁPOLIS" },
  { ddd: 18, state: "SP", name: "MARACAÍ" },
  { ddd: 18, state: "SP", name: "MARABÁ PAULISTA" },
  { ddd: 18, state: "SP", name: "LUTÉCIA" },
  { ddd: 18, state: "SP", name: "LUIZIÂNIA" },
  { ddd: 18, state: "SP", name: "LUCÉLIA" },
  { ddd: 18, state: "SP", name: "LOURDES" },
  { ddd: 18, state: "SP", name: "LAVÍNIA" },
  { ddd: 18, state: "SP", name: "JUNQUEIRÓPOLIS" },
  { ddd: 18, state: "SP", name: "JOÃO RAMALHO" },
  { ddd: 18, state: "SP", name: "ITAPURA" },
  { ddd: 18, state: "SP", name: "IRAPURU" },
  { ddd: 18, state: "SP", name: "INÚBIA PAULISTA" },
  { ddd: 18, state: "SP", name: "INDIANA" },
  { ddd: 18, state: "SP", name: "ILHA SOLTEIRA" },
  { ddd: 18, state: "SP", name: "IEPÊ" },
  { ddd: 18, state: "SP", name: "GUARARAPES" },
  { ddd: 18, state: "SP", name: "GUARAÇAÍ" },
  { ddd: 18, state: "SP", name: "GLICÉRIO" },
  { ddd: 18, state: "SP", name: "GABRIEL MONTEIRO" },
  { ddd: 18, state: "SP", name: "FLORÍNIA" },
  { ddd: 18, state: "SP", name: "FLÓRIDA PAULISTA" },
  { ddd: 18, state: "SP", name: "FLORA RICA" },
  { ddd: 18, state: "SP", name: "EUCLIDES DA CUNHA PAULISTA" },
  { ddd: 18, state: "SP", name: "ESTRELA DO NORTE" },
  { ddd: 18, state: "SP", name: "EMILIANÓPOLIS" },
  { ddd: 18, state: "SP", name: "ECHAPORÃ" },
  { ddd: 18, state: "SP", name: "DRACENA" },
  { ddd: 18, state: "SP", name: "CRUZÁLIA" },
  { ddd: 18, state: "SP", name: "COROADOS" },
  { ddd: 18, state: "SP", name: "CLEMENTINA" },
  { ddd: 18, state: "SP", name: "CASTILHO" },
  { ddd: 18, state: "SP", name: "CÂNDIDO MOTA" },
  { ddd: 18, state: "SP", name: "CAIUÁ" },
  { ddd: 18, state: "SP", name: "CAIABU" },
  { ddd: 18, state: "SP", name: "BURITAMA" },
  { ddd: 18, state: "SP", name: "BREJO ALEGRE" },
  { ddd: 18, state: "SP", name: "BRAÚNA" },
  { ddd: 18, state: "SP", name: "BORÁ" },
  { ddd: 18, state: "SP", name: "BIRIGUI" },
  { ddd: 18, state: "SP", name: "BILAC" },
  { ddd: 18, state: "SP", name: "BENTO DE ABREU" },
  { ddd: 18, state: "SP", name: "BARBOSA" },
  { ddd: 18, state: "SP", name: "AVANHANDAVA" },
  { ddd: 18, state: "SP", name: "ASSIS" },
  { ddd: 18, state: "SP", name: "ARAÇATUBA" },
  { ddd: 18, state: "SP", name: "ANHUMAS" },
  { ddd: 18, state: "SP", name: "ANDRADINA" },
  { ddd: 18, state: "SP", name: "ÁLVARES MACHADO" },
  { ddd: 18, state: "SP", name: "ALTO ALEGRE" },
  { ddd: 18, state: "SP", name: "ALFREDO MARCONDES" },
  { ddd: 18, state: "SP", name: "ADAMANTINA" },
];

const citiesInOrder = cities.sort((a, b) => {
  return a.name < b.name ? -1 : a.name > b ? 1 : 0;
});

export default citiesInOrder;
